service: serverless-hello-world

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  environment:
    ORIGIN: ${file(./config/${self:provider.stage}.yml):origin}

custom:
  origins:
    prod:
      - ${self:provider.environment.ORIGIN}
    dev:
      - ${self:provider.environment.ORIGIN}
      - http://localhost:8080
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    packager: yarn

# Per-function packaging.
package:
  individually: true

# CORS configuration for pre-flighted (OPTIONS) requests.
<<: &cors
  cors:
    origins: ${self:custom.origins.${self:provider.stage}}
    allowCredentials: true

functions:
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: hello-world
          method: get
          <<: *cors
