service: serverless-hello-world

plugins:
  - serverless-webpack

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs8.10

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    packager: yarn

# Per-function packaging.
package:
  individually: true

functions:
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: hello-world
          method: get
          cors: true
